basePath: /
definitions:
  response.CommonResponse:
    properties:
      data: {}
      error: {}
      status:
        type: integer
    type: object
  user.UserLoginRequestBody:
    properties:
      pw:
        type: string
      userID:
        type: string
    type: object
  user.UserRequestBody:
    properties:
      name:
        type: string
      priority:
        type: string
      pw:
        type: string
      role:
        type: string
      spot:
        type: string
      userID:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Cloud Platform API Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: SOMS API
  version: "1.0"
paths:
  /user:
    get:
      consumes:
      - application/json
      description: 사용자의 정보를 전체 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 정보 전체 조회
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 사용자 가입을 진행합니다.
      parameters:
      - description: User Name
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/user.UserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 가입
      tags:
      - user
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: 사용자의 정보를 삭제합니다.
      parameters:
      - description: User uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 정보 삭제
      tags:
      - user
    get:
      consumes:
      - application/json
      description: 사용자의 정보를 조회합니다.
      parameters:
      - description: User uuid
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 정보 조회
      tags:
      - user
  /user/{userID}:
    patch:
      consumes:
      - application/json
      description: 사용자의 정보를 수정합니다.
      parameters:
      - description: User ID
        in: path
        name: UserID
        required: true
        type: string
      - description: User Name
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/user.UserRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 정보 수정
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 사용자 로그인을 진행합니다.
      parameters:
      - description: User Login Info
        in: body
        name: UserLogin
        required: true
        schema:
          $ref: '#/definitions/user.UserLoginRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 로그인
      tags:
      - user
  /user/validate/{userID}:
    get:
      consumes:
      - application/json
      description: 사용자 ID의 유효성을 검사합니다.
      parameters:
      - description: User ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResponse'
      summary: 사용자 ID 유효성 검사
      tags:
      - user
swagger: "2.0"
